#In this template we changed the date 2010 and appropriate quotations. We then took added quotations to the BucketPolicy string literal. restructured the outputs and placed the S3 website and domain the special functions. After implementing those changes I restructured the who template until the template was validated.
#Revision Number #: 1
#Date: 8/13/2025

AWSTemplateFormatVersion: '2010-09-09'
Resources:
    S3Bucket:
        Type: 'AWS::S3::Bucket'
        Properties:
          PublicAccessBlockConfiguration:
            BlockPublicAcls: false
            BlockPublicPolicy: false
            IgnorePublicAcls: false
            RestrictPublicBuckets: false
          WebsiteConfiguration:
            IndexDocument: index.html
            ErrorDocument: error.html
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
    BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref S3Bucket
            PolicyDocument:
                Id: MyPolicy
                Version: 2012-10-17
                Statement:
                    - Sid: PublicReadForGetBucketObjects
                      Effect: Allow
                      Principal: '*'
                      Action: 's3:GetObject'
                      Resource: !Join 
                        - ''
                        - - 'arn:aws:s3:::'
                          - !Ref S3Bucket
                          - '/*'
Outputs:
    WebsiteURL:
        Description: S3 Hosted Website
        Value: !GetAtt S3Bucket.github.com/chajen9503/S3
    S3BucketSecureURL:
        Value: !Join 
            - ''
            - - 'https://'
              - !GetAtt S3Bucket.github
        Description: Name of S3 bucket to hold website content